spring:
  application:
    name: spring-openai

  datasource:
    url: jdbc:mysql://localhost:3306/openai
    username: root
    password: Alifpass@49
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    show-sql: true

  ai:
    openai:
      api-key: ${OPEN_API_KEY}

server:
  port: 9876